const fs = require('node:fs');
const path = require('node:path');
const esbuild = require('esbuild');
const project = path.resolve(__dirname, '..');

async function build() {
  const dictionary = path.join(project, 'node_modules', 'dictionary-uk');
  const result = await esbuild.build({
    absWorkingDir: project,
    entryPoints: ['worker-entry.js'], bundle: true, write: false, minify: true,
    platform: 'browser', target: ['es2022'], charset: 'utf8',
    plugins: [{
      name: 'local-dictionary', setup(build) {
        build.onResolve({ filter: /^rvn-dictionary$/ }, () => ({ path: 'rvn-dictionary', namespace: 'dictionary' }));
        build.onLoad({ filter: /.*/, namespace: 'dictionary' }, () => ({
          contents: 'module.exports=' + JSON.stringify({ aff: fs.readFileSync(path.join(dictionary, 'index.aff'), 'utf8'), dic: fs.readFileSync(path.join(dictionary, 'index.dic'), 'utf8') }),
          loader: 'js'
        }));
      }
    }]
  });
  // A Blob worker with embedded data also works when index.html is opened via file://.
  fs.writeFileSync(path.join(project, 'proofreading-worker.js'), '/* Generated by scripts/build.cjs. Licenses and dictionary source: vendor/. */\nwindow.RVN_WORKER_SOURCE = ' + JSON.stringify(result.outputFiles[0].text) + ';\n');
  const vendor = path.join(project, 'vendor');
  fs.mkdirSync(vendor, { recursive: true });
  for (const name of ['index.aff', 'index.dic', 'license', 'readme.md']) fs.copyFileSync(path.join(dictionary, name), path.join(vendor, name === 'license' ? 'dictionary-uk-GPL-3.0.txt' : 'dictionary-uk-' + name));
  fs.copyFileSync(path.join(project, 'node_modules', 'nspell', 'license'), path.join(vendor, 'nspell-MIT.txt'));
  const isBuffer = path.join(path.dirname(require.resolve('nspell')), '..', '..', 'is-buffer', 'LICENSE');
  if (fs.existsSync(isBuffer)) fs.copyFileSync(isBuffer, path.join(vendor, 'is-buffer-MIT.txt'));
  console.log('Built offline worker (' + Math.round(result.outputFiles[0].contents.length / 1024) + ' KiB); dictionary source and licenses copied to vendor/.');
}
build().catch(error => { console.error(error); process.exitCode = 1; });
